docs/readme.md
This timeout could show up due to local network.
=> Activate all components in default and polish doc

Makefile.in, deploy/platform/kubernetes/feature-cluster/resources.yaml, deploy/platform/kubernetes/feature-single-node/resources.yaml
Closes https://github.com/apache/skywalking/issues/8130
=> Add alarm feature to demo, fix control plane metrics not work

Makefile.in
@kezhenxu94 I think we need a redeploy after merged.
=> Update OAP to avoid CVE as exposed on demo env

Makefile.in
Follow https://github.com/apache/skywalking-java/pull/128
=> Update Java agent to fix thread pool metric

deploy/platform/kubernetes/feature-cluster/resources.yaml
- Open ALS_TCP_ANALYSIS
- Use  `mx-mesh` to unify mesh service name
- Set `SW_SLOW_DB_THRESHOLD` to make slow DB query
=> Update oap environment variables

Makefile.in, deploy/platform/kubernetes/feature-agent/profiling.yaml, deploy/platform/kubernetes/feature-rover/permissions.yaml, deploy/platform/kubernetes/feature-rover/profiling.yaml, deploy/platform/kubernetes/feature-rover/resources.yaml, docs/readme.md
* Add Rover into the Kubernetes environment
* The Rover is not supported running in the docker-compose environment
* Add Trace and eBPF Profiling Cron Job
=> Add Rover into the Kubernetes environment

services/app/ui/src/App.js, services/app/ui/src/index.js
Reverts apache/skywalking-showcase#45 as it breaks the booting.
@arugal is taking a look.
=> Revert "Simulate errors for client-js"

Makefile.in, services/songs-service/Dockerfile, services/songs-service/build.gradle, services/songs-service/src/main/java/org/apache/skywalking/showcase/services/song/controller/SongController.java
Close https://github.com/apache/skywalking/issues/9556
=> Add virtual cache show case

Makefile.in
The pr is related to https://github.com/apache/skywalking/issues/9625.
=> Bump up swck version to v0.7.0

deploy/platform/kubernetes/feature-slowsql-mysql/fluent-bit.yaml, deploy/platform/kubernetes/feature-slowsql-mysql/mysql.yaml, deploy/platform/kubernetes/feature-slowsql-mysql/shared-volume.yaml, docs/readme.md
FYI @yswdqz in case you want to add psql by referencing this
=> Add feature slow sql to showcase using mysql as example

Makefile.in
Sync a fix for long-time critical bugs
- https://github.com/apache/skywalking/pull/9710
- https://github.com/apache/skywalking/pull/9690
=> Bump up the OAP version

deploy/platform/docker/Makefile, deploy/platform/docker/docker-compose.vm.yaml
=> [8.x] Update docker-compose to docker compose

Makefile.in
Relate to https://github.com/apache/skywalking-java/pull/397
=> Bump up java agent version

Makefile.in, deploy/platform/kubernetes/feature-event/scaler.yaml, deploy/platform/kubernetes/feature-rover/profiling.yaml
1. Sync the tag with the rover and backend
2. Remote the `mesh-svr::recommendation` in the scaling and update it as the network profiling service
=> Sync rover and change the network profiling service

services/songs-service/src/main/java/org/apache/skywalking/showcase/services/song/mq/SongMessageReceiver.java
Use auto ack to avoid re-consume
=> Fix incorrect acknowledgeMode on consumer side

Makefile.in
Activate the latest updates
- PromQL(not exposed yet)
- S3 monitoring on UI menu
- DynamoDB monitoring on UI emnu
=> Bump OAP and UI version

deploy/platform/kubernetes/Chart.yaml, deploy/platform/kubernetes/Makefile, deploy/platform/kubernetes/templates/NOTES.txt, deploy/platform/kubernetes/templates/_helpers.tpl, deploy/platform/kubernetes/templates/feature-event/resources.yaml, deploy/platform/kubernetes/values.yaml
so that we don't have to use `index` function to access the values, which is error-prune and not development friendly
=> Add alias for Charts that contains `-`

deploy/platform/kubernetes/values.yaml
Satellite will be enable in Makefile.in and should be disabled here by default unless it is activated explicitly
=> Allow disabling satellite deployment

.github/workflows/publish-images.yaml, Makefile.in, deploy/platform/docker/docker-compose.agent.yaml, deploy/platform/docker/docker-compose.cluster.yaml, deploy/platform/docker/docker-compose.single-node.yaml, deploy/platform/kubernetes/templates/feature-agent/resources.yaml, docs/readme.md, services/rating-service/Dockerfile, services/rating-service/Dockerfile.agentless, services/rating-service/Makefile, services/rating-service/go.mod, services/rating-service/main.go, services/recommendation-service/src/app.py
=> Adding go service

deploy/platform/kubernetes/templates/feature-rover/resources.yaml
Following https://github.com/apache/skywalking-showcase/pull/157#discussion_r1459191440, update the namespaces to the helm variable.
=> Update the exclude namespaces with helm variable

Makefile.in, deploy/platform/kubernetes/templates/feature-rabbitmq-monitor/opentelemetry-config.yaml
=> change RabbitMQ opentelemetry config for hierarchy

deploy/platform/docker/config/pulsar/otel-collector-config.yaml, deploy/platform/docker/docker-compose.cluster.yaml, deploy/platform/docker/docker-compose.pulsar-monitor.yaml, deploy/platform/docker/docker-compose.single-node.yaml, deploy/platform/kubernetes/Makefile, deploy/platform/kubernetes/Makefile.in, deploy/platform/kubernetes/templates/feature-pulsar-monitor/opentelemetry-config.yaml, deploy/platform/kubernetes/templates/feature-pulsar-monitor/resource.yaml, deploy/platform/kubernetes/templates/otel-collector-config.yaml, deploy/platform/kubernetes/values.yaml, docs/readme.md
Ref https://github.com/apache/skywalking/issues/11939
=> Add pulsar showcase

Makefile.in, deploy/platform/docker/Makefile.in, deploy/platform/docker/docker-compose.mongodb-monitor.yaml, deploy/platform/docker/docker-compose.pulsar-monitor.yaml, deploy/platform/docker/docker-compose.rocketmq-monitor.yaml, docs/readme.md
- Fix previous docker configuration mistakes
- Update [oap](https://github.com/apache/skywalking/tree/48c96a233103ba869143062923d4033678b91f73) and [ui](https://github.com/apache/skywalking-booster-ui/tree/8bc67614681b37623fa64233f8389d6754e64cf2)
=> Fix docker configurations and bump up images

deploy/platform/kubernetes/templates/feature-postgresql-monitor/fluent-bit.yaml
PR includes:
- Bug fix in fluent bit lua script 
- Discussed [here](https://github.com/apache/skywalking/discussions/12168#discussioncomment-9257487)
=> Fixing time bug in fluent bit lua script

Makefile.in
=> Bump OAP and UI

Makefile.in, deploy/platform/docker/docker-compose.elasticsearch-monitor.yaml, deploy/platform/docker/docker-compose.pulsar-monitor.yaml, deploy/platform/docker/docker-compose.rocketmq-monitor.yaml, deploy/platform/docker/scripts/es-e2e-data-mock.sh
```
make undeploy.docker
```
command have some error.  so i fix it
=> fix docker deploy with make undeploy.docker

deploy/platform/docker/docker-compose.cluster.yaml, deploy/platform/docker/docker-compose.single-node.yaml, deploy/platform/kubernetes/values.yaml
enable java-agent meter analyzer file by default.
=> Enable java-agent meter analyzer file.

deploy/platform/kubernetes/templates/feature-r3/resources.yaml
Following https://github.com/apache/skywalking-showcase/pull/189#discussion_r1795041293
=> Delete curl in the `r3-load`

Makefile.in, deploy/platform/docker/config/flink/otel-collector-flink-config.yaml, deploy/platform/docker/docker-compose.cluster.yaml, deploy/platform/docker/docker-compose.flink-monitor.yaml, deploy/platform/docker/docker-compose.single-node.yaml, deploy/platform/kubernetes/Makefile, deploy/platform/kubernetes/templates/feature-flink/opentelemetry-config.yaml, deploy/platform/kubernetes/templates/feature-flink/resource.yaml, deploy/platform/kubernetes/templates/otel-collector-config.yaml, deploy/platform/kubernetes/values.yaml, docs/readme.md
=> Add flink monitoring showcase
